project_identifier_env: CROWDIN_REACT_PROJECT_ID
api_key_env: CROWDIN_REACT_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/content/docs/*.md'
    translation: '/docs/%locale%/docs/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'af': 'af'
        'ar': 'ar'
        'bs-BA': 'bs-BA'
        'ca': 'ca'
        'cs': 'cs'
        'da': 'da'
        'de': 'de'
        'el': 'el'
        'es-ES': 'es-ES'
        'fa': 'fa-IR'
        'fi': 'fi'
        'fr': 'fr'
        'he': 'he'
        'hu': 'hu'
        'id': 'id-ID'
        'it': 'it'
        'ja': 'ja'
        'ko': 'ko'
        'mr': 'mr-IN'
        'nl': 'nl'
        'no': 'no-NO'
        'pl': 'pl'
        'pt-BR': 'pt-BR'
        'pt-PT': 'pt-PT'
        'ro': 'ro'
        'ru': 'ru'
        'sk': 'sk-SK'
        'sr': 'sr'
        'sv-SE': 'sv-SE'
        'tr': 'tr'
        'uk': 'uk'
        'vi': 'vi'
        'zh-CN': 'zh-Hans'
        'zh-TW': 'zh-Hant'
  -
    source: '/content/blog/*.md'
    translation: '/docs/%locale%/blog/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/tutorial/*.md'
    translation: '/docs/%locale%/tutorial/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/community/*.md'
    translation: '/docs/%locale%/community/%original_file_name%'
    ignore:
      - '/content/community/complementary-tools.it-IT.md'
      - '/content/community/complementary-tools.ko-KR.md'
      - '/content/community/complementary-tools.zh-CN.md'
      - '/content/community/conferences.it-IT.md'
      - '/content/community/conferences.ko-KR.md'
      - '/content/community/conferences.zh-CN.md'
      - '/content/community/examples.it-IT.md'
      - '/content/community/examples.ko-KR.md'
      - '/content/community/examples.zh-CN.md'
      - '/content/community/videos.it-IT.md'
      - '/content/community/videos.ko-KR.md'
      - '/content/community/videos.zh-CN.md'
    languages_mapping: *anchor
  -
    source: '/content/contributing/*.md'
    translation: '/docs/%locale%/contributing/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/warnings/*.md'
    translation: '/docs/%locale%/warnings/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/README.md'
    translation: '/docs/%locale%/README.md'
    languages_mapping: *anchor
  -
    source: '/content/404.md'
    translation: '/docs/%locale%/404.md'
    languages_mapping: *anchor
