backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "Docs"
    folder: "/content/docs"
    create: true
    fields:
      - { name: "permalink", label: "路由-结尾为.html" }
      - { name: "title", label: "Title", widget: "string"}
      - { name: "body", label: "Body", widget: "markdown" }
